### ISSUE TITLE
`qx lint` fails because of missing @babel/plugin-syntax-jsx

### ISSUE THREAD

**Issue by rad-pat** [qooxdoo/qooxdoo#10356]
I'm getting a problem with qx lint since I decided I'd bring myself up to date with latest beta release.  I have installed the framework with `npm install -g @qooxdoo/framework@7.0.0-beta.8` but when I try to `qx lint` my project, I get a bunch of these:
```
/home/plaid/www/PlaidClient/plaid/source/class/plaid/util/format/__init__.js: line 0, col 0, Error - Parsing error: Cannot find module '@babel/plugin-syntax-jsx'
Require stack:
- /home/plaid/.nvm/versions/node/v14.17.4/lib/node_modules/@qooxdoo/framework/node_modules/@babel/core/lib/config/files/plugins.js
- /home/plaid/.nvm/versions/node/v14.17.4/lib/node_modules/@qooxdoo/framework/node_modules/@babel/core/lib/config/files/index.js
- /home/plaid/.nvm/versions/node/v14.17.4/lib/node_modules/@qooxdoo/framework/node_modules/@babel/core/lib/index.js
- /home/plaid/.nvm/versions/node/v14.17.4/lib/node_modules/@qooxdoo/framework/lib/compiler/index.js
- /home/plaid/.nvm/versions/node/v14.17.4/lib/node_modules/@qooxdoo/framework/bin/deploy/qx

438 problems
```
I checked in the node_modules path given, no @babel subfolder at all
`qx compile` is working fine
I tried `npm install -g @babel/plugin-syntax-js` but the errors remain.

This was on Ubuntu 18.04 for my development environment, but I'm also seeing it in our Dockerfile that provides linting.
Interestingly, it seems to run `qx lint` just fine on the Qooxdoo library I have in a submodule folder right next to my app, though that does appear to have a well populated local node_modules. I must've ran the bootstrap there I guess.

**Comment by hkollmann** [comment]
Should be work with @7.0.0-beta.9!

**Comment by hkollmann** [comment]
@rad-pat : Could you check and close the issue?

**Comment by rad-pat** [comment]
Apologies, I was away on vacation. The fix is working for me. 👍
