### ISSUE TITLE
TypeError: document.msElementsFromPoint is not a function on Firefox v59.0b1

### ISSUE THREAD

**Issue by paragasu** [qooxdoo/qooxdoo#9481]
This error only appear in the Firefox browser console right after i upgrade the firefox version to v59.0b1 (Firefox Developer Edition), 
On the console also mention the related js file `TouchCore.js:398`

I am running the lastest version of qooxdoo (commit 382e296ec029845d7903b361a5ccd8943a3d55c9)
Firefox v59.0b1 (Firefox Developer Edition) on Debian Linux

To reproduce, 
1. Git pull the latest commit on qooxdoo
2. Upgrade Firefox version to the latest Firefox Developer Edition v59.0b1
3. Reload qooxdoo project on the browser
4. See the above error appearing a few times on the console.

**Comment by level420** [comment]
The call to `document.msElementsFromPoint` comes from https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/event/handler/TouchCore.js#L398 in method `qx.event.handler.TouchCore.__evaluateTarget`.
This method is called in `qx.event.handler.TouchCore._getTarget `, but only if `qx.core.Environment.get("event.mspointer")` is `true`.

@pragasu could you please check (via console) which value `qx.core.Environment.get("event.mspointer")` has in firefox v59.0b1? Thank you.

Firefox v59.0b1 is still only available as a developer edition.

**Comment by paragasu** [comment]
hi @level420,

The value of `qx.core.Environment.get("event.mspointer")` is `true`.

`msElementsFromPoint` has been rename to only `elementsFromPoint` in Firefox?

**Comment by paragasu** [comment]
Setting the env `event.mspointer` in the config.json will make the error disappear otherwise everytime i move the pointer will generate the above error.

**Comment by paragasu** [comment]
Renaming the `document.msElementsFromPoint` to `document.elementFromPoint` at `TouchCore.js:398` seem to solve the problem.

**Comment by level420** [comment]
Firefox implemented since v41 `PointerEvent` but did not enable them by default.
See:
 https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/PointerEvent
 https://www.w3.org/TR/pointerevents/

To enable them til (obviously) v59 they had to be activated in the preferences in about:config `dom.w3c_pointer_events.enabled` by setting it to `true`.

Now it seems that they will enable them by default in v59.

@paragasu please open `about:config` in your firefox v59 and check the value of `dom.w3c_pointer_events.enabled` and report back. Thank you.

**Comment by level420** [comment]
Yep! That's it: I've set `dom.w3c_pointer_events.enabled` to true in my Firefox v58 and now I can see that error message as well.

The failing code is commented to be af fix only for IE10 which was introduced with commit https://github.com/qooxdoo/qooxdoo/commit/b016e2a22e4813cea955899b514d9c30d4a94261#diff-553374637eec64b4739bead3bcca7f64 in 2012 with a fix for issue https://github.com/qooxdoo/qooxdoo/issues/6973

**Comment by level420** [comment]
The fix is applied for
```javascript
if(qx.core.Environment.get("event.mspointer")) {
 .....
}
```
but it should be applied for
```javascript
if(qx.core.Environment.get("engine.name") == "mshtml" &&
   qx.core.Environment.get("browser.documentmode") < 10) {
   ....
}
```
Will prepare a PR soon.

**Comment by level420** [comment]
@paragasu could you please check if PR #9483 solves this issue? Thank you!

**Comment by paragasu** [comment]
The value of `dom.w3c_pointer_events.enabled` in my `about:config` is also `true`.
Yes PR #9483 solve the problem.

**Comment by hkollmann** [comment]
Fixed with PR #9483

**Comment by level420** [comment]
@paragasu thank you for reporting this issue!
